// This file is auto-generated by Supabase CLI
// Run: npx supabase gen types typescript --project-id [PROJECT-REF] > lib/supabase/database.types.ts
// For now, we'll use a minimal type definition

export type Database = {
  public: {
    Tables: {
      users: {
        Row: {
          id: string
          email: string
          phone: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          email: string
          phone?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          email?: string
          phone?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      // Add other tables as needed
    }
  }
}



